config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :articles
  devise_for :users, controllers: { registrations: "registrations"}
  resources :guides
  resources :contacts, only: [:new, :create]
  get '/about', to: 'welcome#about'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_attached_file :image, styles: { medium: "750x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_attached_file :cover, styles: { thumb: "300x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

  extend FriendlyId
	friendly_id :title, use: :slugged
  is_impressionable
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
  	{
  		:subject => "Contact Form",
  		:to => "varma.santosh@outlook.com",
  		:from => %("#{name}" <#{email}>)
    }
	end
end

app/models/guide.rb
class Guide < ApplicationRecord
  has_attached_file :image, styles: { medium: "750x500>", thumb: "400x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  extend FriendlyId
	friendly_id :title, use: :slugged
  is_impressionable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all.order("updated_at desc").paginate(page: params[:page], per_page: 9)
  end

  def show
    impressionist(@article)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new article_params

		if @article.save
			redirect_to @article, notice: "Article posted successfully!"
		else
			render 'new', notice: "Oh no, Unable to post your article."
		end
  end

  def update
    if @article.update article_params
			redirect_to @article, notice: "Article is updated!"
		else
			render 'edit'
		end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
		params.require(:article).permit(:title, :content, :slug, :image, :cover)
	end

	def find_article
		@article = Article.friendly.find(params[:id])
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render 'new'
		end
	end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :find_guide, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @guides = Guide.all.order("updated_at desc").paginate(page: params[:page], per_page: 9)
  end

  def show
    impressionist(@guide)
  end

  def new
    @guide = Guide.new
  end

  def edit
  end

  def create
    @guide = Guide.new guide_params

		if @guide.save
			redirect_to @guide, notice: "Guide posted successfully!"
		else
			render 'new', notice: "Oh no, Unable to post your Guide."
		end
  end

  def update
    if @guide.update guide_params
			redirect_to @guide, notice: "Guide is updated!"
		else
			render 'edit'
		end
  end

  def destroy
    @guide.destroy
    redirect_to guides_path
  end

  private

  def guide_params
		params.require(:guide).permit(:title, :content, :slug, :image)
	end

	def find_guide
		@guide = Guide.friendly.find(params[:id])
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if ((User.count == 1) & (user_signed_in?))
      redirect_to root_path
    elsif User.count == 1
      redirect_to new_user_session_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@guides = Guide.all.limit(3).order("created_at desc")
		@articles = Article.all.limit(3).order("updated_at desc")
	end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_intended_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_config = function () {
	this.page.url = '<%= url_for ([@article, {only_path: false}]) %>';
  this.page.identifier = 'article_<%= @article.id %>';
  this.page.title = '<%= @article.title %>';
};

	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');

	s.src = '//codevarma.disqus.com/embed.js';

	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<%= form_for @article, html: { multipart: true } do |f| %>
  <% if @article.errors.any? %>
     <h2><%= pluralize(@article.errors.count, "error") %> prevented this article from saving:</h2>
     <ul>
     	<% @article.errors.full_messages.each do |m| %>
     	   <li><%= m %></li>
     	<% end %>
     </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>


  <br>
  <br>

  <%= f.label :content, "Write your article here" %><br>
  <%= f.text_area :content %>

  <br>
  <br>

  <%= f.label :image %><br>
	<%= f.file_field :image %>

	<br>
	<br>

  <%= f.label :cover %><br>
	<%= f.file_field :cover %>

  <br>
  <br>

  <%= f.submit %>

<% end %>

app/views/articles/edit.html.erb
<header>
	<title><%= @article.title %> | CodeVarma</title>
</header>

<h1 id="page_title">Edit Aricle</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<header>
	<title>Articles | CodeVarma</title>
</header>

<h1 id="page_title">Stuff I've Written</h1>

<div id="projects">
	<% @articles.each do |article| %>
		<div class="project">
			<div class="project_image">
				<% if article.cover.present? %>
					<%= link_to (image_tag article.cover.url(:thumb)), article %>
				<% end %>
			</div>
			<div class="project_content">
				<h2><a href="#"><%= link_to article.title, article %></a> &nbsp; &nbsp;<i class="fa fa-eye" aria-hidden="true"></i> <%= article.impressionist_count %></h2>
			</div>
		</div>
	<% end %>
</div>

<%= will_paginate @articles %>

app/views/articles/new.html.erb
<header>
	<title>New Article | CodeVarma</title>
</header>

<h1 id="page_title">New Article</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<header>
	<title><%= @article.title %> | CodeVarma</title>
</header>

<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<h1><%= @article.title %></h1>
		<hr>
	</header>

	<div id="content">
		<p><%= markdown @article.content %></p>
	</div>
	<div>
		<hr>
		<p style="text-align: center;"></a><i class="fa fa-eye" aria-hidden="true"></i> <%= @article.impressionist_count %> views </p>
		<% if @article.image.present? %>
			<hr>
			<%= image_tag @article.image.url(:medium) %>
		<% end %>
	</div>
	<% if user_signed_in? %>
	<div id="admin_links">
		<%= link_to "Edit Article", edit_article_path(@article) %>
	    <%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>
	</div>
	<% end %>

	<hr>

	<div id="share_box">
		<p>Share</p>
		<!-- Twitter -->
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @article.title %> by @codevarma - &amp;url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
		<hr>
		<p class="post" style="margin-top: 10px;"><a href="/contacts/new" class="show_button show_button_wrapper">direct message</a></p>
	</div>

	<hr>

	<%= render 'disqus' %>

	<hr>

</div>

app/views/contacts/create.html.erb
<header>
	<title>Thank you | CodeVarma</title>
</header>

<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for your message!</h1>
	<p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<header>
	<title>Say Hello! @codevarma</title>
</header>

<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name %><br>
		<%= f.text_field :name, required: true %>

		<br>

		<%= f.label :email %><br>
		<%= f.email_field :email, required: true %>

		<br>

		<%= f.label :message %><br>
		<%= f.text_area :message, as: :text %>

		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'leave this field blank' %>
		</div>

		<%= f.submit 'Send Message', class: "button" %>
	<% end %>
</div>

app/views/guides/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_config = function () {
	this.page.url = '<%= url_for ([@guide, {only_path: false}]) %>';
  this.page.identifier = 'guide_<%= @guide.id %>';
  this.page.title = '<%= @guide.title %>';
};

	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');

	s.src = '//codevarma.disqus.com/embed.js';

	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/guides/_form.html.erb
<%= form_for @guide, html: { multipart: true } do |f| %>
  <% if @guide.errors.any? %>
     <h2><%= pluralize(@guide.errors.count, "error") %> prevented this guide from saving:</h2>
     <ul>
     	<% @guide.errors.full_messages.each do |m| %>
     	   <li><%= m %></li>
     	<% end %>
     </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :content, "Write your guide here" %><br>
  <%= f.text_area :content %>

  <br>
  <br>

  <%= f.label :image %><br>
	<%= f.file_field :image %>

	<br>
	<br>

  <%= f.submit %>

<% end %>

app/views/guides/edit.html.erb
<header>
	<title>Edit Guide | CodeVarma</title>
</header>

<h1 id="page_title">Edit Guide</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/guides/index.html.erb
<header>
	<title>Guides | CodeVarma</title>
</header>

<h1 id="page_title">Guides on Basic Rails</h1>

<div id="projects">
	<% @guides.each do |guide| %>
		<div class="project">
			<div class="project_image">
				<% if guide.image.present? %>
					<%= link_to (image_tag guide.image.url(:thumb)), guide %>
				<% end %>
			</div>
			<div class="project_content">
				<h2><a href="#"><%= link_to guide.title, guide %></a> &nbsp; &nbsp;<i class="fa fa-eye" aria-hidden="true"></i> <%= guide.impressionist_count %></h2>
			</div>
		</div>
	<% end %>
</div>


<%= will_paginate @guides %>

app/views/guides/new.html.erb
<header>
	<title>New Guide | CodeVarma</title>
</header>

<h1 id="page_title">New Guide</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/guides/show.html.erb
<header>
	<title><%= @guide.title %> | CodeVarma</title>
</header>

<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<h1><%= @guide.title %></h1>
		<hr>
	</header>

	<div id="content">
		<p><%= markdown @guide.content %></p>
	</div>

	<div>
		<hr>
		<p style="text-align: center;"></a><i class="fa fa-eye" aria-hidden="true"></i> <%= @guide.impressionist_count %> views </p>
	</div>

	<% if user_signed_in? %>
	<div id="admin_links">
		<%= link_to "Edit Guide", edit_guide_path(@guide) %>
	    <%= link_to "Delete Guide", guide_path(@guide), method: :delete, data: { confirm: "Are you sure?" } %>
	</div>
	<% end %>

	<hr>

	<div id="share_box">
		<p>Share</p>
		<!-- Twitter -->
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @guide.title %> by @codevarma - &amp;url=<%= url_for([@guide, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@guide, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@guide, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
		<hr>
		<p class="post" style="margin-top: 10px;"><a href="/contacts/new" class="show_button show_button_wrapper">direct message</a></p>
	</div>

	<hr>

	<%= render 'disqus' %>

	<hr>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<link rel="icon" href="images/codev2.png" type="image/png">
		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<header id="main_navigation" class="clearfix">
			<a href="/" class="name"><<span class="light">code</span><span class="blue">varma</span>></a>
			<nav>
				<a href="https://jvssvarma.github.io" target="_blank"><i class="fa fa-code" aria-hidden="true"></i> Work</a> &nbsp;
				<a href="/about"><i class="fa fa-user" aria-hidden="true"></i> About</a> &ensp;
				<a href="/guides"><i class="fa fa-lightbulb-o" aria-hidden="true" style="font-size: 1.1rem;"></i></i> Guides</a> &nbsp;
				<a href="/articles"><i class="fa fa-book" aria-hidden="true"></i> Articles</a> &nbsp;
				<a href="/contacts/new" class="show_button show_button_wrapper"><i class="fa fa-envelope" aria-hidden="true"></i> Contact</a>
				<% if user_signed_in? %>
				    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
				<% end %>
			</nav>
		</header>
		<% if notice %>
			<p class="notice"><%= notice %></p>
		<% elsif alert %>
			<p class="alert"><%= alert %></p>
		<% end %>

		<%= yield %>

		<div id="footer">
			<p class="copyright">&copy;2016 jvssvarma</p>
			<nav>
				<a href="http://twitter.com/codevarma" target="_blank"><i class="fa fa-twitter"></i></a>
	      <a href="https://www.instagram.com/santoshcreative" target="_blank"><i class="fa fa-instagram"></i></a>
				<a href="http://github.com/jvssvarma" target="_blank"><i class="fa fa-github"></i></a>
			</nav>
		</div>
	</body>
</html>

app/views/welcome/about.html.erb
<header>
  <title>About | CodeVarma</title>
</header>

<h1 id="page_title"> About Me </h1>

<div id="about_wrapper" class="skinny_wrapper_about">
  <h5 class="post">Hi! I'm Jampana Varma<br/>Future Software Craftsman. Coding &amp; Development are my passion and the amazing ocean of opportunities it has is what drives my passion. I spend most of my time learning and working on new stuff.</h5>
  <h4 class="about_list">Techs I'm learning, have knowledge, worked and used:</h4>
  <a frameborder="0" data-theme="dark" data-stack-embed="true" data-layers="1,2,3,4" href="https://embed.stackshare.io/stacks/embed/232b282c0d69eb"/></a><script async src="https://cdn1.stackshare.io/javascripts/client-code.js" charset="utf-8"></script>
  <p class="post" style="margin-top: 10px;">Send me a <a href="/contacts/new" class="show_button show_button_wrapper">direct message</a></p>
  <p class="post">You can see my work on <a href="http://github.com/jvssvarma" target="_blank" class="show_button show_button_wrapper">Github</a></p>
  <p>(Please feel free to look through my work and if you are interested in working with me don't hesitate to get in touch! You can find me speaking in 140 characters on Twitter, posting pictures on instagram and sharing some code on Github.)</p>

  <p class="post">See my project portfolio @<a href="http://jampanavarma.me" target="_blank"> jampanavarma.me</a></p>
  <p class="post_link"><a href="http://twitter.com/codevarma" target="_blank"><i class="fa fa-twitter"></i></a> &nbsp; <a href="http://github.com/jvssvarma" target="_blank"><i class="fa fa-github"></i></a></p>

</div>

app/views/welcome/index.html.erb
<header>
	<title>CodeVarma | Articles on Rails</title>
</header>

<div class="wrapper wrapper_padding clearfix">
	<div class="about homepage_content">
    <h2>Articles &amp; Guides on adding features or building apps using<span class="half_red">Ruby Gems</span> in <span class="green">Rails Applications</span> and other simple web practices.</h2>
    <h3>Hi! I'm <span class="blue">jvssvarma</span> &amp; thank you for visiting <span class="orange">CodeVarma</span>. Checkout my blogs, articles, projects &amp; guides.</h3>
	</div>
	<br>
	<br>
	<div class="center col-1 posts_content">
		<h2>Recently added Guides</h2>
		<% @guides.each do |guide| %>
			<h3><a href="#"><%= link_to guide.title, guide %></a></h3>
			<p class="date"><%= guide.created_at.strftime("%A, %b %d") %></p>
		<% end %>

	</div>
	<div class="center col-1 projects_content">
		<h2>Recent Articles</h2>
		<% @articles.each do |article| %>
			<h3><a href="#"><%= link_to article.title, article %></a></h3>
			<p class="date"><%= article.created_at.strftime("%A, %b %d") %></p>
		<% end %>
	</div>
</div>